[package]
name = "iaido"
version = "0.1.0"
authors = ["Daniel Leong <me@dhleong.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for cleaner tests:
indoc = "1.0"

# "ui"
crossterm = { version = "0.19" }
tui = { version = "0.14", default-features = false, features = ["crossterm"] }

genawaiter = "0.99.1"
telnet = "0.1.4"
url = "2.2.0"
vte = "0.10.0"
tokio = { version = "1.2.0", features = ["full"] }
