[package]
name = "iaido"
version = "0.1.0"
authors = ["Daniel Leong <me@dhleong.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.19" }
tui = { version = "0.14", default-features = false, features = ['crossterm'] }

genawaiter = "0.99.1"

# for cleaner tests:
indoc = "1.0"
